### ISSUE TITLE
插件报错

### ISSUE THREAD

**Issue by Lorikein12138** [Apricityx/minecraft-rcon-command-remake#1]
RCON正常连接后反馈
连接失败 TypeError: Cannot read properties of undefined (reading 'split')

**Comment by Apricityx** [comment]
现在还有这个问题吗

**Comment by NorLorikein** [comment]
> 现在还有这个问题吗

有的

**Comment by Apricityx** [comment]
是否方便附上完整日志与配置信息



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月1日(周日) 下午3:48
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [Apricityx/minecraft-rcon-command-remake] 插件报错 (Issue #1)




  
现在还有这个问题吗
  
有的
